vocabulary = {
    "abolish": "отменять",
    "addicted to": "зависимый от",
    "adventurous": "любящий приключения",
    "age difference": "разница в возрасте",
    "any other": "любой другой",
    "anxious": "тревожный",
    "approachable": "доступный",
    "unapproachable": "недоступный",
    "appropriate": "подходящий",
    "inappropriate": "неподходящий",
    "bore": "зануда",
    "bossy": "властный",
    "break into": "вламываться",
    "break up": "расставаться",
    "bring up": "воспитывать",
    "busybody": "сплетник",
    "campaign": "кампания",
    "canteen": "столовая",
    "caption": "подпись",
    "care": "забота",
    "cautious": "осторожный",
    "committed": "преданный",
    "competitive": "соперничающий",
    "complementary": "дополняющий",
    "compromise": "компромисс",
    "constant": "постоянный",
    "constantly": "постоянно",
    "control": "контроль",
    "convinced": "убежденный",
    "dare": "осмеливаться",
    "dismissively": "пренебрежительно",
    "disobey": "не подчиняться",
    "diversity": "разнообразие",
    "down to a fine art": "довести до совершенства",
    "drum": "барабанить",
    "dull": "скучный",
    "encouragement": "поддержка",
    "endearing": "милый",
    "engineering": "инженерия",
    "entirely": "полностью",
    "especially": "особенно",
    "exclude": "исключать",
    "expertise": "компетенция",
    "face value": "номинал",
    "fiddle with": "теребить",
    "forgetful": "забывчивый",
    "frustrated": "расстроенный",
    "frustrating": "разочаровывающий",
    "generation gap": "разрыв поколений",
    "get back together": "сойтись снова",
    "get your own way": "добиваться своего",
    "homemaker": "домохозяйка",
    "hopeless": "безнадежный",
    "hunter": "охотник",
    "ignorant": "невежественный",
    "impulsively": "импульсивно",
    "incompatible": "несовместимый",
    "infantile": "инфантильный",
    "inferior": "уступающий",
    "intriguing": "интригующий",
    "knowledgeable": "знающий",
    "language barrier": "языковой барьер",
    "left wing": "левый",
    "loser": "неудачник",
    "march": "марш",
    "mature": "зрелый",
    "modest": "скромный",
    "moody": "угрюмый",
    "moodiness": "капризность",
    "out of control": "вне контроля",
    "out of touch": "оторванный от реальности",
    "pay attention": "обращать внимание",
    "personality trait": "черта личности",
    "predictably": "предсказуемо",
    "unpredictable": "непредсказуемый",
    "provoke": "провоцировать",
    "pushiness": "навязчивость",
    "rant and rave": "кричать",
    "reasonable": "разумный",
    "reassuring": "обнадеживающий",
    "relaxed": "расслабленный",
    "remain": "оставаться",
    "responsible": "ответственный",
    "irresponsible": "безответственный",
    "right wing": "правый",
    "ruthless": "безжалостный",
    "sensitive": "чувствительный",
    "insensitive": "нечувствительный",
    "shed a tear": "проронить слезу",
    "small talk": "светская беседа",
    "space cadet": "рассеянный человек",
    "spend ages": "тратить вечность",
    "spoil": "баловать",
    "spoilt": "избалованный",
    "stand up to sb": "противостоять",
    "stem from": "проистекать из",
    "sticker": "наклейка",
    "strangely": "странно",
    "sulk": "дутся",
    "superior": "превосходящий",
    "sympathetic with sb": "сочувствующий",
    "taboo": "табу",
    "take for granted": "принимать как должное",
    "temper": "характер",
    "tense": "напряженный",
    "thats rubbish": "это чепуха",
    "treatment": "обращение",
    "traditionally": "традиционно",
    "uncertainty": "неопределенность",
    "uniqueness": "уникальность",
    "unwanted": "нежеланный",
    "valid": "обоснованный",
    "walk all over sb": "вытирать ноги",
    "well-matched": "хорошо подходящие",
    "well-behaved": "воспитанный",
    "well-balanced": "уравновешенный",
    "withdraw into a world of your own": "уйти в свой мир",
    "worrying": "тревожный"
}

